package com.houstondirectauto.refurb.enums;

public enum VehicleStatus {
    IN_TRANSIT, ARBITRATION, INSPECTION, ASSIGNED, IN_REVIEW, APPROVED, SERVICE_IN_NEED, READY_CARS,
    RE_INSPECT, PENDING_PSI, FAILED_PSI, IDMS_SOLD, IDMS_NOT_FOUND, WHOLESALE, CONTRACT_CONFIRMATION,
    RENTAL, PENDING_REFUND
}
